#!/bin/sh
set -e

case "$1" in
    remove)
    [ -f /etc/default/packagename ] && . /etc/default/packagename
    [ -z "$PACKAGENAME_USER" ] && PACKAGENAME_USER="packagename"
    # Remove auth for packagename to open privileged ports via authbind.
    PACKAGENAME_UID="`id -u $PACKAGENAME_USER`"
    if [ -f "/etc/authbind/byuid/$PACKAGENAME_UID" ]; then
        rm -f /etc/authbind/byuid/$PACKAGENAME_UID
    fi
    ;;
esac

# Automatically added by dh_installinit
if [ -x "/etc/init.d/packagename" ] || [ -e "/etc/init/packagename.conf" ]; then
    invoke-rc.d packagename stop || true
fi
# End automatically added section
