---
name: CI
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - master
jobs:
  ci-build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
#        os: [ ubuntu-latest, windows-latest ]
        #os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 8 ]
#        java: [ 8, 11, 14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: docker version
        run: docker version
      - name: docker info
        run: docker info
      - name: java version
        run: java -version
      - name: clean build
        run: ./gradlew clean build --no-daemon --info --stacktrace
        timeout-minutes: 10
#      - name: clean build
#        run: ./gradlew clean build -x validatePomFileForPluginMavenPublication --no-daemon --info --stacktrace
#        timeout-minutes: 10
...
